name: First
on: [push,workflow_dispatch]
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: checck out code
              uses: actions/checkout@v3
            - name: Installing dependncies
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install dependencies
              run: npm ci

              